### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by dreamhighchina** [wangzhe0623/Object-Detection-Evaluation-Tool#2]
大佬，跑你的demo，都有问题：
Num of prediction files:  729
Num of ground truth files:  721
groundtruths' size does not match predictions' size， please check ~ 
Traceback (most recent call last):
  File "test.py", line 70, in <module>
    eval.run()
  File "/home/112831/code/tools/Eval_object_detection-master/evaluation.py", line 272, in run
    prediction_path, gt_path, predictions, groundtruths, file_format = self.load_all_files()
TypeError: cannot unpack non-iterable int object

**Comment by JohnSuuAries** [comment]
你这数据有问题啊，prediction 和我ground truth 数量都不一样。检查下吧。

--------------原始邮件--------------
发件人："dreamhighchina "<notifications@github.com>;
发送时间：2019年10月11日(星期五) 上午10:58
收件人："wangzhe0623/Object-Detection-Evaluation-Tool" <Object-Detection-Evaluation-Tool@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[wangzhe0623/Object-Detection-Evaluation-Tool] demo (#2)
-----------------------------------

 
大佬，跑你的demo，都有问题：
 Num of prediction files:  729
 Num of ground truth files:  721
 groundtruths' size does not match predictions' size， please check ~
 Traceback (most recent call last):
 File "test.py", line 70, in 
 eval.run()
 File "/home/112831/code/tools/Eval_object_detection-master/evaluation.py", line 272, in run
 prediction_path, gt_path, predictions, groundtruths, file_format = self.load_all_files()
 TypeError: cannot unpack non-iterable int object

**Comment by dreamhighchina** [comment]
大佬，我用的是你的数据，我什么都没有改，求大佬指教下

**Comment by dreamhighchina** [comment]
要不大佬你下载这个跑跑，是不是后来修改了，我就下载了你的，然后什么都没有动，包括数据。

**Comment by dreamhighchina** [comment]
大佬可以了，删除了里面几个空的文件就好了

**Comment by dreamhighchina** [comment]
大佬，这两个参数的含义是什么？？
overlapRatio': 0.5,
 'threshold': 0.5,

**Comment by wangzhe0623** [comment]
@wangzhe0623 兄弟，overlapRatio是ground truth和预测框的IOU；threshold是置信度阈值，prec和rec就是在这个阈值下计算的。
